// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FaqPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"mx-6 my-8\"><h2 class=\"text-2xl font-bold\">FAQs</h2><section class=\"my-4\"><h3 class=\"text-lg font-semibold\">What is office games?</h3><p>An online tracker for games. You can create an office which is a space you can invite others to. You can then create multiple games for an office which each have their own ranking systems.</p></section><section class=\"my-4\"><h3 class=\"text-lg font-semibold\">How our ELOs calculated?</h3><p>Every player starts on 400 ELO points. When a match is played, an expected score is calculated with the two players ELOs (in the case of a team game, the team's ELO is the average of each of the players)...</p><div class=\"flex justify-center items-center gap-2 my-4\"><span>Expected=</span><div><p class=\"text-center mx-auto\">1</p><hr><p class=\"text-center mx-auto\">1 + 10<sup>(loserElo-winnerElo)/400</sup></p></div></div><p>...then the ELO gained/lost can be calculated with the following...</p><div class=\"flex justify-center my-4\">&pm; ELO = 32 * (1 - Expected)</div><p>Before applying ELO to the participants, there are a couple of checks:</p><ul class=\"list-disc my-4\"><li>Minimum ELO is 200. If applying the ELO puts a player below that, they just stay at 200.</li><li>A players first 20 matches are double points (gain and loss) to move them more quickly to their proper ranking.</li></ul></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
